changed description of 'ziele', background on mobile version and breakpoints
ScrumpliCity/ScrumpliCity pull request #10
Opened 2024-10-08 15:17 UTC by dasechtelima

![image](https://github.com/user-attachments/assets/d0c5ecd2-08aa-4c5b-a4d7-81ca64555f0e)

![image](https://github.com/user-attachments/assets/f10638f0-3c8a-4a5f-b540-54f64ac718c5)

2024-10-08 19:16 UTC, soplikessoup requested changes
Die Bullet Points bei "Features unserer Website" sind etwas unübersichtlich - unterschiedliche Bullet Points würden die Hierarchien schneller erkennbar machen.
Sonst Design top :)

2024-10-09 06:53 UTC, soplikessoup approved these changes
Design passt :)

2024-10-09 20:58 UTC, felixwollmann requested changes
ich bin zwar nicht design-mensch, hab trotzdem folgende anmerkungen:

![image](https://github.com/user-attachments/assets/231f2c1d-5e83-4002-b19f-a6b0551ace69)
da ist der text ziemlich schmal in der mitte, beabsichtigt?


![image](https://github.com/user-attachments/assets/0745b201-a113-41d4-9133-39ac16171599)
Die Bullet Points beginnen da ganz am linken rand, das sieht weird aus

2024-10-09 20:58 UTC, felixwollmann commented on diplomarbeit/app.vue
> +          <ul class="list-inside ml-8" style="list-style: circle">
statt inline styles lieber tailwind arbitrary values verwenden

2024-10-09 20:58 UTC, felixwollmann commented on diplomarbeit/app.vue
> +            <li>Review-Meetings inkl. Velocity Berechnung</li>
```suggestion
            <li>Review-Meetings inkl. Velocity-Berechnung</li>
```
da gehört im Deutschen ein Bindestrich

2024-10-10 07:25 UTC, felixwollmann approved these changes

2024-10-10 07:33 UTC, merged