SC-57: Sprint Planning
ScrumpliCity/ScrumpliCity pull request #120
Opened 2024-12-14 22:04 UTC by felixwollmann

2024-12-28 09:29 UTC, dasechtelima requested changes
mein größter Respekt, das ist insane was du da gemacht hast, nur paar Kleinigkeiten noch :)

2024-12-28 09:29 UTC, dasechtelima commented on frontend/pages/play/sprint-planning.vue
mein Fehler, habs im Mockup nicht hingeschrieben, allerdings haben wir uns darauf geeinigt, die URL mit /play/sprints/[nummer]/[phasenbezeichnung] zu machen, also in dem Fall für den ersten Sprint /play/sprints/1/planning

2024-12-28 09:29 UTC, dasechtelima commented on frontend/pages/play/sprint-planning.vue
> +    ></Timer>
auf meinem normalen Laptop Bildschirm ist der Timer über der Detailbox, wäre schön wenn die Box da etwas niedriger wird (wenn Platz ist, sonst liegt der Timer einfach drüber), außerdem fände ich es gut wenn der Timer nicht durchsichtig ist sondern weiß, dann ist das Problem mit drüberliegen auch nicht so schlimm
![image](https://github.com/user-attachments/assets/dfd5f3c1-d06f-4fff-941f-df9fb15c4ec3)

2024-12-28 21:14 UTC, felixwollmann commented on frontend/pages/play/sprint-planning.vue
okay gut zu wissen weil über dieses Faktum hat mich bis dato noch niemand informiert

2024-12-28 21:15 UTC, felixwollmann commented on frontend/pages/play/sprint-planning.vue
> +    ></Timer>
okay, pass ich an, dann könnt ma aber realistische bildschirmgrößen bitte auch im design berücksichtigten, danke :)

2024-12-29 10:36 UTC, dasechtelima approved these changes

2024-12-29 10:41 UTC, merged