SC-2: Startseite
ScrumpliCity/ScrumpliCity pull request #134
Opened 2024-12-28 17:52 UTC by dasechtelima

whoop whoop eine responsive Startseite

2024-12-28 22:20 UTC, felixwollmann requested changes
die implementierung ist halt eher bescheiden von der qualität her, also ich könnte hier unendlich screenshots anfügen von bildschirmgrößen, bei der das design nicht wirklich passt

jedenfalls gut dass du fertig bist und wir endlich eine annehmbare startseite haben :)

2024-12-28 22:20 UTC, felixwollmann commented on frontend/components/HomeHeader.vue
> +            style="opacity: 100"
bitte tailwind, keine inline styles

2024-12-28 22:20 UTC, felixwollmann commented on frontend/pages/index.vue
> +          <span v-html="$t('homepage.project_description')"></span>
wozu v-html? :) das ist ja gar kein html

2024-12-28 22:20 UTC, felixwollmann commented on frontend/i18n/locales/en.json
> +    "project_description": "Learn the agile project management method Scrum by building a paper city! ScrumpliCity provides a web application, crafting templates and explanations about Scrum - so: {b
du greifst auf den parameter `build_your_scrum_knowledge zu, den du aber beim übersetzen nie übergibst

2024-12-28 22:20 UTC, felixwollmann commented on frontend/i18n/locales/en.json
> +        "description": "Discover the basics of Scrum and start your first agile project - practical, interactive and easy to understand!"
bitte den richtigen dash verwenden

2024-12-28 22:20 UTC, felixwollmann commented on frontend/i18n/locales/en.json
>    }
bitte unter homepage geben

2024-12-28 22:20 UTC, felixwollmann commented on frontend/pages/index.vue
![image](https://github.com/user-attachments/assets/327547d8-10f2-4217-8972-ff92b5eba3f3)
ich bekomme einen hydration mismatch

2024-12-28 22:20 UTC, felixwollmann commented on frontend/pages/index.vue
> +          ></UTooltip
ebenso bitte tailwind und nicht inline styles

2024-12-28 22:20 UTC, felixwollmann commented on frontend/pages/index.vue
> +            <h3
die icons sind noch dort, wo sie laut mockup sein sollten

implementiert:
![image](https://github.com/user-attachments/assets/31febe9b-fe07-406e-b49c-51732dcff144)

mockup;
![image](https://github.com/user-attachments/assets/a0318614-7813-4e75-bb17-ceb3d85a8f11)

2024-12-28 22:30 UTC, dasechtelima commented on frontend/pages/index.vue
> +      :close-button="null"
ich hab gegoogelt, anders bekommt man den close-button nicht weg und er muss aber weg

2024-12-29 00:04 UTC, felixwollmann commented on frontend/pages/index.vue
> +      :close-button="null"
das heißt du willst jetzt immer von deiner werten IDE einen Fehler angezeigt bekommen??? hast du nicht nach eine lösung dafür gesucht?
die gibt's und sie heißt @ts-expect-error

2024-12-29 11:28 UTC, dasechtelima commented on frontend/pages/index.vue
> +      :close-button="null"
und wohin soll ich das schreiben? über `:close-button="null"` sind keine comments erlaubt

2024-12-30 09:14 UTC, dasechtelima commented on frontend/components/HomeHeader.vue
> +            style="opacity: 100"
ich kann die opacity über class="opacity-100" nicht setzen, auch nicht über das :ui vom nuxt component, deshalb so

2024-12-30 09:15 UTC, felixwollmann commented on frontend/components/HomeHeader.vue
> +            style="opacity: 100"
was geht daran nicht?

2024-12-30 09:17 UTC, felixwollmann commented on frontend/components/HomeHeader.vue
> +            style="opacity: 100"
wenn Spezifizität dann halt !opacity-100

2024-12-30 09:18 UTC, dasechtelima commented on frontend/pages/index.vue
> +          <span v-html="$t('homepage.project_description')"></span>
damit das `&shy;` für die Projektmanagementmethode funktioniert :)

2024-12-30 09:18 UTC, felixwollmann commented on frontend/pages/index.vue
> +      :close-button="null"
wo es halt funktioniert, jedenfalls werden wir sicher nicht für immer einen TypeScript Fehler in unserem Projekt haben.

2024-12-30 09:27 UTC, felixwollmann commented on frontend/pages/index.vue
> +      :close-button="null"
Googlen verrät mir es gibt sowas wie `<!-- @vue-expect-error`

2024-12-30 09:47 UTC, dasechtelima commented on frontend/pages/index.vue
> +      :close-button="null"
das hab ich rausgefunden, war nur zu blöd dafür es anzuwenden, ist drin

2025-01-01 15:19 UTC, felixwollmann commented on frontend/pages/index.vue
> +});
scrollToTopButtonIsVisible sollte computed werden und nicht in einem watch geupdatet werden

2025-01-01 15:19 UTC, felixwollmann commented on frontend/pages/index.vue
> +};
```suggestion
const scrollToTopOfPage = () => {
  y.value = 0;
};
```
das geht auch mit diesem Composable

2025-01-01 15:19 UTC, felixwollmann commented on frontend/pages/index.vue
> +      <!--@vue-expect-error-->
```suggestion
      <!--@vue-expect-error ':close-button="null" is the way to hide the close button but incorrectly not allowed by types -->
```
eine Beschreibung macht es in der Zukunft leichter

2025-01-01 15:19 UTC, felixwollmann commented on frontend/i18n/locales/en.json
> +    "project_description": "Learn the agile project management method Scrum by building a paper city! ScrumpliCity provides a web application, crafting templates and explanations about Scrum - so: ",
```suggestion
    "project_description": "Learn the agile project management method Scrum by building a paper city! ScrumpliCity provides a web application, crafting templates and explanations about Scrum—so: ",
```

2025-01-01 15:19 UTC, felixwollmann commented on frontend/i18n/locales/de.json
> +    "scrum_guide_description": "Du möchtest dich außerhalb des Spielprozesses über die agile Projektmanagement&shy;methode Scrum weiterbilden? Auf unserer Scrum-Theorie-Seite findest du alles Wichtig
```suggestion
    "scrum_guide_description": "Du möchtest dich außerhalb des Spielprozesses über die agile Projektmanagement&shy;methode Scrum weiterbilden? Auf unserer Scrum-Theorie-Seite findest du alles Wichtige: von den Grundlagen bis zu praktischen Tipps. Egal, ob du neu einsteigst oder dein Wissen vertiefen möchtest – hier bekommst du klare, verständliche Erklärungen. Schau vorbei und bring deine Projekte auf das nächste Level!",
```
Gedankenstriche im Deutschen sind Halbgeviertstriche

2025-01-01 15:19 UTC, felixwollmann commented on frontend/i18n/locales/de.json
> +        "description": "Entdecke die Grundlagen von Scrum und starte dein erstes agiles Projekt — praxisnah, interaktiv und einfach verständlich!"
```suggestion
        "description": "Entdecke die Grundlagen von Scrum und starte dein erstes agiles Projekt – praxisnah, interaktiv und einfach verständlich!"
```

2025-01-01 15:19 UTC, felixwollmann commented on frontend/i18n/locales/de.json
> +    "project_description": "Lerne die agile Projektmanagement\u00ADmethode Scrum mittels Bau einer Papierstadt! ScrumpliCity stellt eine Web-Applikation, Bastelvorlagen und Erklärungen zu Scrum zur V
```suggestion
    "project_description": "Lerne die agile Projektmanagement\u00ADmethode Scrum mittels Bau einer Papierstadt! ScrumpliCity stellt eine Web-Applikation, Bastelvorlagen und Erklärungen zu Scrum zur Verfügung – also: ",
```

2025-01-01 15:19 UTC, felixwollmann commented on frontend/i18n/locales/en.json
> +        "description": "Discover the basics of Scrum and start your first agile project — practical, interactive and easy to understand!"
```suggestion
        "description": "Discover the basics of Scrum and start your first agile project—practical, interactive and easy to understand!"
```
Wenn ein em-dash (Geviertstrich), dann ohne Leerzeichen davor und danach. Oder ein Halbgeviertstrich (n-dash), dann mit Leerzeichen davor und danach. Beides richtig, nur halt dabei bleiben überall.

2025-01-01 15:19 UTC, felixwollmann commented on frontend/pages/index.vue
> +            <h3
![image](https://github.com/user-attachments/assets/b58e8788-ad47-48e0-92b5-81bccd6be786)
das ist noch immer der fall, zwar nicht mehr im deutschen, aber im englischen

2025-01-01 15:25 UTC, felixwollmann requested changes
kleinigkeiten noch :)

2025-01-01 15:25 UTC, felixwollmann commented on frontend/components/HomeHeader.vue
> +      </UButton>
das ist noch immer der fall
![image](https://github.com/user-attachments/assets/eeb8ed80-7a29-4b00-be26-79b7cd41fb4d)

2025-01-01 15:25 UTC, felixwollmann commented on frontend/components/HomeFooter.vue
> +            class="hover:text-sc-orange"
```suggestion
            class="hover:text-sc-orange transition-colors"
```

2025-01-01 15:25 UTC, felixwollmann commented on frontend/components/HomeFooter.vue
> +            class="hover:text-sc-orange"
```suggestion
            class="hover:text-sc-orange transition-colors"
```

2025-01-01 15:25 UTC, felixwollmann commented on frontend/components/HomeFooter.vue
> +            class="hover:text-sc-orange"
```suggestion
            class="hover:text-sc-orange transition-colors"
```

2025-01-01 15:25 UTC, felixwollmann commented on frontend/components/HomeFooter.vue
> +          class="text-xs hover:text-sc-orange xl:text-base"
```suggestion
          class="text-xs hover:text-sc-orange xl:text-base transition-colors"
```

2025-01-01 15:25 UTC, felixwollmann commented on frontend/components/HomeHeader.vue
> +        class="flex items-center justify-between hover:text-sc-orange"
```suggestion
        class="flex items-center justify-between hover:text-sc-orange transition-colors"
```

2025-01-01 15:25 UTC, felixwollmann commented on frontend/components/HomeHeader.vue
> +            class="text-sc-black hover:text-sc-orange"
```suggestion
            class="text-sc-black hover:text-sc-orange transition-colors"
```

2025-01-01 15:25 UTC, felixwollmann commented on frontend/components/HomeHeader.vue
> +            class="text-sc-black hover:text-sc-orange"
```suggestion
            class="text-sc-black hover:text-sc-orange transition-colors"
```

2025-01-01 15:25 UTC, felixwollmann commented on frontend/components/HomeHeader.vue
> +          class="hover:text-sc-orange"
```suggestion
          class="hover:text-sc-orange transition-colors"
```

2025-01-01 15:25 UTC, felixwollmann commented on frontend/components/HomeHeader.vue
> +            class="hidden h-8 !opacity-100 drop-shadow-sc-shadow hover:bg-orange-700 lg:block"
```suggestion
            class="hidden h-8 !opacity-100 drop-shadow-sc-shadow hover:bg-orange-700 lg:block transition-colors"
```

2025-01-03 21:05 UTC, felixwollmann approved these changes
ich glaub du wirst wieder auf chrome schimpfen, es gibt noch einen overflow :)

2025-01-03 21:05 UTC, felixwollmann commented on frontend/pages/index.vue
> +    <div class="absolute top-12 z-10 flex w-screen justify-center lg:hidden">
```suggestion
    <div class="absolute top-12 z-10 flex w-full justify-center lg:hidden">
```
es gibt noch immer einen overflow
![image](https://github.com/user-attachments/assets/0bb59c74-b2c3-4a55-915c-04079fed556d)

2025-01-04 08:09 UTC, merged