SC-57: Sprint Planning Backend
ScrumpliCity/ScrumpliCity pull request #137
Opened 2024-12-29 21:43 UTC by felixwollmann

abhängigkeit von der lehrkraftübersicht, deswegen halt alles, was ohne der schon geht

2025-01-02 17:15 UTC, felixwollmann commented
dependant on @Pycxtv's game overview

2025-02-16 23:12 UTC, Pycxtv commented
Concerning the routing based on the current phase of the game: Works nicely at first sight, however, it is still possible to jump back to other phases and even sprints by changing the url.
In that scenario, of course, no timer countdown can be displayed (which is totally fine and makes sense), but this screen shouldn't be accessible at all in that scenario.

![image](https://github.com/user-attachments/assets/0c4cc5d7-bdb5-44a2-8e78-bb54d013e0e9)

2025-02-17 06:59 UTC, Pycxtv commented
Also please only show info text in the first sprint.

2025-02-17 06:59 UTC, Pycxtv requested changes

2025-02-21 00:14 UTC, Pycxtv commented on frontend/middleware/auth.ts
Not 100% sure but I think this is causing me not being able to visit the login page and thus not being able to create and manage a room 🤷‍♂️

![image](https://github.com/user-attachments/assets/a196017c-4af2-4de8-aa03-279ee0e5477e)

2025-02-21 00:15 UTC, Pycxtv commented on frontend/middleware/auth.ts
Therefore it's hard to test any other functionality.

2025-02-21 14:52 UTC, Pycxtv requested changes
Nicely done, just address the issues and it should be ready for merging.

2025-02-21 14:52 UTC, Pycxtv commented on frontend/pages/play/[sprint]/planning.vue
Minor usability bug: The field below the timer expands too high up and blocks the view of the tooltip when the timer of the room is paused:

![image](https://github.com/user-attachments/assets/bfd64369-53ec-48e7-bb92-e226e7a7a15d)

2025-02-21 14:52 UTC, Pycxtv commented on frontend/middleware/ensurePlaying.ts
There is the problem that, if a team decides to join during a game, it gets redirected before it even can set members (the guard needs some sort of an exception for the team/members page

2025-02-22 19:01 UTC, Pycxtv approved these changes
Nice job

2025-02-22 20:26 UTC, merged