Projektwebsite
ScrumpliCity/ScrumpliCity pull request #2
Opened 2024-09-12 08:09 UTC by dasechtelima

2024-09-12 18:05 UTC, felixwollmann requested changes
sehr schön! :)
ein paar kleine änderungen noch bitte :)

2024-09-12 18:05 UTC, felixwollmann commented on diplomarbeit/app.vue
> +  <div class="bg-sc-white flex flex-col scroll-smooth bg-[url('/assets/img/bg-houses.svg')] bg-no-repeat bg-[center_top_20rem] sm:bg-[url('/assets/img/bg-houses-desktop.svg')] sm:bg-[center_top_18rem
```suggestion
  <div class="bg-sc-white flex flex-col scroll-smooth bg-[url('/assets/img/bg-houses.svg')] bg-no-repeat bg-[center_top_20rem] sm:bg-[url('/assets/img/bg-houses-desktop.svg')] sm:bg-[center_top_18rem] sm:bg-contain min-h-[100svh]">
```
wenn man ganz rausscrollt ist der hintergrund dann immer noch da

2024-09-12 18:05 UTC, felixwollmann commented on diplomarbeit/app.vue
> +      <p class="text-justify sm:mb-20 text-sm sm:text-xl leading-6 sm:leading-9 mx-8 sm:mx-[400px]">
```suggestion
      <p class="text-justify sm:mb-20 text-sm sm:text-xl leading-6 sm:leading-9 mx-8 sm:mx-[400px] max-w-[80ch]">
```

2024-09-12 18:05 UTC, felixwollmann commented on diplomarbeit/app.vue
> +      <h1 class="sm:scroll-mt-36 text-3xl font-logo sm:text-6xl" id="/">
```suggestion
      <h1 class="sm:scroll-mt-36 text-3xl font-logo sm:text-6xl">
```
wertlose Id

2024-09-14 12:23 UTC, felixwollmann approved these changes
die Manrope bitte noch committen und entsprechend .gitignore anpassen, dann ist's gut :)

2024-09-14 12:23 UTC, felixwollmann commented on diplomarbeit/assets/css/main.css
die dürfen wir aber schon commiten, kein sinn darin die zu verstecken

2024-09-14 12:56 UTC, soplikessoup requested changes
logo noch falsch sonst top :)

2024-09-14 12:56 UTC, soplikessoup commented on diplomarbeit/assets/img/schriftlogo.svg
falsches Logo -> siehe Teams/Assets/svg

2024-09-14 13:17 UTC, soplikessoup approved these changes

2024-09-14 13:17 UTC, merged